{"uid":"92ad3281713880d9","name":"User is not allowed to enter alpha characters","fullName":"tests.test_login.TestLogin#test_invalid_input_number","historyId":"86204b0d5df43d727e4b2a0dade23e08","time":{"start":1684826901452,"stop":1684826903837,"duration":2385},"description":"User is not allowed to enter alpha characters","descriptionHtml":"<p>User is not allowed to enter alpha characters</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":2,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684826874788,"stop":1684826901448,"duration":26660},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter alpha characters","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684826901453,"stop":1684826902686,"duration":1233},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684826902686,"stop":1684826903705,"duration":1019},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'aaaa'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"167cd88c9f383176","name":"stdout","source":"167cd88c9f383176.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":2,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684826903838,"stop":1684826904741,"duration":903},"status":"passed","steps":[],"attachments":[{"uid":"910e439f42579f0b","name":"Screenshot","source":"910e439f42579f0b.png","type":"image/png","size":200562}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"firefox"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"e7a5f6497e16"},{"name":"thread","value":"18-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'firefox'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"c68226ec4d55fc7d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614051,"stop":1684826614051,"duration":0}},{"uid":"1611473186442ec1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f23ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531276,"stop":1684826531276,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"3466d084f7378e2c","reportUrl":"../4/index.html#testresult/3466d084f7378e2c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614051,"stop":1684826614051,"duration":0}},{"uid":"daaf7e82af56579e","reportUrl":"../3/index.html#testresult/daaf7e82af56579e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f23ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531276,"stop":1684826531276,"duration":0}}]},"tags":["firefox","@pytest.mark.usefixtures('setup')"]},"source":"92ad3281713880d9.json","parameterValues":["'firefox'"]}