{"name": "User is able to login,this should fail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15", "trace": "self = <tests.test_login.TestLogin object at 0x10d99c750>\n\n    @allure.description(\"User is able to login\")\n    @allure.title(\"User is able to login,this should fail\")\n    def test_user_login(self):\n>       self.login_page.login_existing_user(\n            \"01116888790\", \"test\", \"alyaothman\")\n\ntests/test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:56: in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\npages/nav_bar_page.py:25: in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\npages/base_page.py:33: in get_text\n    element: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"35adf6d4d70f89eb1fa478b8426947e4\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x10d9d1620>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       0   chromedriver                        0x0000000100967598 chromedriver + 4973976\nE       1   chromedriver                        0x000000010095e913 chromedriver + 4938003\nE       2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\nE       3   chromedriver                        0x000000010055f2ff chromedriver + 746239\nE       4   chromedriver                        0x000000010055f591 chromedriver + 746897\nE       5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\nE       6   chromedriver                        0x00000001005839ed chromedriver + 895469\nE       7   chromedriver                        0x000000010059e856 chromedriver + 1005654\nE       8   chromedriver                        0x0000000100583793 chromedriver + 894867\nE       9   chromedriver                        0x000000010055121f chromedriver + 688671\nE       10  chromedriver                        0x000000010055256e chromedriver + 693614\nE       11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\nE       12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\nE       13  chromedriver                        0x000000010092d40f chromedriver + 4736015\nE       14  chromedriver                        0x000000010092791a chromedriver + 4712730\nE       15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\nE       16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\nE       17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\nE       18  chromedriver                        0x000000010095828f chromedriver + 4911759\nE       19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\nE       20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15\n\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException"}, "description": "User is able to login", "steps": [{"name": "User logs in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/alya/Documents/selenium-ci-cd/pages/login_page.py\", line 56, in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/alya/Documents/selenium-ci-cd/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/alya/Documents/selenium-ci-cd/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "User clicks login icon in nav bar", "status": "passed", "start": 1684825090955, "stop": 1684825093328}, {"name": "Fill phone number", "status": "passed", "parameters": [{"name": "phone_number", "value": "'01116888790'"}], "start": 1684825093328, "stop": 1684825097909}, {"name": "User clicks start exploring", "status": "passed", "start": 1684825097909, "stop": 1684825098841}, {"name": "User fill password", "status": "passed", "parameters": [{"name": "password", "value": "'test'"}], "start": 1684825098841, "stop": 1684825100390}, {"name": "User clicks login button", "status": "passed", "start": 1684825100391, "stop": 1684825101493}, {"name": "Return username when user logged in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/alya/Documents/selenium-ci-cd/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/alya/Documents/selenium-ci-cd/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1684825101493, "stop": 1684825133110}], "parameters": [{"name": "phone_number", "value": "'01116888790'"}, {"name": "password", "value": "'test'"}, {"name": "username", "value": "'alyaothman'"}], "start": 1684825090955, "stop": 1684825133119}], "attachments": [{"name": "stderr", "source": "9ae7d6d9-3b01-4a0c-90c8-0f052b641814-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1684825090955, "stop": 1684825133127, "uuid": "1da6dca7-f67f-4e35-947f-4a26ad687420", "historyId": "c70b764e14c198ae23bb359c5cb1e46d", "testCaseId": "0edf0a627e33dcf0062a7d9e3e848ac1", "fullName": "tests.test_login.TestLogin#test_user_login", "labels": [{"name": "tag", "value": "chrome"}, {"name": "story", "value": "Login functionality"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "40403-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}